### ISSUE TITLE
what are the XSS concerns?

### ISSUE THREAD

**Issue by jake-101** [galvez/nuxt-json-data#3]
What is the worry behind XSS with this module?

**Comment by galvez** [comment]
Third party script may be able to overwrite the contents of:

```js
document.getElementById('__NUXT_JSON_DATA__').textContent
```

A potential workaround is to use a [Blake3](https://www.npmjs.com/package/blake3) hash based on the contents of the script instead of `__NUXT_JSON_DATA__`. What do you think @pi0 @Atinux @pimlie @aldarund? :)

**Comment by pi0** [comment]
@galvez Would you please elaborate more on how hash digest of data can prevent that?

**Comment by galvez** [comment]
@pi0 I'm thinking something like using devalue for the hash, then validating function runs Blake3 on the received payload against the devalued hash. Is that too far fetched? Am I missing something? :)
